using System;
using System.Drawing;
using System.IO;
using System.Reflection;
using System.Windows.Forms;
using Application = System.Windows.Application;
using MessageBox = System.Windows.MessageBox;

namespace MW;

internal sealed class TrayController : IDisposable
{
    private readonly NotifyIcon _icon;
    private readonly Action _onShowPicker;
    private readonly Action _onEditRegions;
    private readonly Action _onAbout;
    private readonly Action _onCheckUpdates;
    private readonly Action _onQuit;

    public TrayController(Action onShowPicker, Action onEditRegions, Action onAbout,
                          Action onCheckUpdates, Action onQuit)
    {
        _onShowPicker = onShowPicker;
        _onEditRegions = onEditRegions;
        _onAbout = onAbout;
        _onCheckUpdates = onCheckUpdates;
        _onQuit = onQuit;

        _icon = new NotifyIcon
        {
            Visible = true,
            Text = "MW — Mikkel's Workspace",
            Icon = LoadTrayIcon(),
        };
        _icon.ContextMenuStrip = BuildMenu();
        _icon.DoubleClick += (_, _) => _onShowPicker();
    }

    private static Icon LoadTrayIcon()
    {
        // Resource path generated by WPF for content under Assets/.
        try
        {
            var asm = Assembly.GetExecutingAssembly();
            using var s = asm.GetManifestResourceStream("MW.Assets.tray.ico");
            if (s != null) return new Icon(s);
        }
        catch { /* fall through */ }
        return SystemIcons.Application;
    }

    private ContextMenuStrip BuildMenu()
    {
        var menu = new ContextMenuStrip();
        menu.Items.Add("Snap to Region", null, (_, _) => _onShowPicker());
        menu.Items.Add("Edit Regions for All Displays…", null, (_, _) => _onEditRegions());
        menu.Items.Add(new ToolStripSeparator());
        menu.Items.Add("About MW", null, (_, _) => _onAbout());
        menu.Items.Add("Check for Updates…", null, (_, _) => _onCheckUpdates());
        menu.Items.Add(new ToolStripSeparator());
        menu.Items.Add("Quit", null, (_, _) => _onQuit());
        return menu;
    }

    public void Dispose()
    {
        _icon.Visible = false;
        _icon.Dispose();
    }
}
